name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup default stable

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build release binary
      run: |
        source $HOME/.cargo/env
        cargo build --release

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ordinator-macos
        path: target/release/ordinator
        retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4

    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        path: dist/

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/ordinator-macos
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 