name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --all-features

    - name: Security audit
      run: cargo audit --deny warnings

    - name: Build release binary
      run: cargo build --release

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ordinator-macos
        path: target/release/ordinator
        retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v4

    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        path: dist/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/ordinator-macos
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    name: Update Homebrew Formula
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Get SHA256 hash
      id: get_sha256
      run: |
        SHA256=$(curl -sL "https://github.com/${{ github.repository }}/archive/${{ steps.get_version.outputs.VERSION }}.tar.gz" | shasum -a 256 | cut -d' ' -f1)
        echo "SHA256=$SHA256" >> $GITHUB_OUTPUT

    - name: Checkout homebrew tap
      uses: actions/checkout@v4
      with:
        repository: ceterus/homebrew-ordinator
        token: ${{ secrets.GITHUB_TOKEN }}
        path: homebrew-tap

    - name: Update formula
      run: |
        cd homebrew-tap
        sed -i "s|url \"https://github.com/ceterus/ordinator/archive/v[0-9.]*\.tar\.gz\"|url \"https://github.com/ceterus/ordinator/archive/${{ steps.get_version.outputs.VERSION }}.tar.gz\"|" Formula/ordinator.rb
        sed -i "s|sha256 \"[a-f0-9]*\"|sha256 \"${{ steps.get_sha256.outputs.SHA256 }}\"|" Formula/ordinator.rb

    - name: Commit and push formula update
      run: |
        cd homebrew-tap
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Formula/ordinator.rb
        git commit -m "Update ordinator to ${{ steps.get_version.outputs.VERSION }}"
        git push 